### ISSUE TITLE
FatalExecutionEngineError 0xc0000005

### ISSUE THREAD

**Issue by vanlooverenkoen** [tebjan/Sanford.Multimedia.Midi#12]
Hi, 

When I try to close an inputDevice I get this error:

FatalExecutionEngineError
  Adress =  0x4aabcfa4
  FaultCode = 0xc0000005

I don't know what this means. Or what I am doing wrong? This is the way how I do it at the moment:
```
        public void StopListeningMidi()
        {
            _inDevice?.StopRecording();
            _inDevice?.Close();
        }
```

also this way doesn't work
```
        public void StopListeningMidi()
        {
            _inDevice?.StopRecording();
            _inDevice?.Reset();
            _inDevice?.Close();
        }
```
 Can someone help me how I close an inputDevice correctly?

**Comment by tebjan** [comment]
are you using the latest version?have you build it from the repo? and have you read this issue? https://github.com/tebjan/Sanford.Multimedia.Midi/issues/4

**Comment by vanlooverenkoen** [comment]
I'm using 6.1.2 version via NuGet. And I'm reading the issue atm. But I need .NET 4.5

**Comment by tebjan** [comment]
ok, the just compile the latest sources and you should be fine. there was already a fix for this. the nuget will be updated soon as well...
https://github.com/tebjan/Sanford.Multimedia.Midi/pull/10

**Comment by vanlooverenkoen** [comment]
Aah oke perfect, where will you post this if the nuget is updated?

**Comment by vanlooverenkoen** [comment]
This is my first project with libaries in .NET how do I get the compiled latest Sources? because when I clone this project and then import project -> I select the sources .csproj . but when I run the my program I get the same error. Is this the right way of doing this or do I need to do something else?

**Comment by tebjan** [comment]
i would build a dll with release config from the latest sources and use that dll in your project... also make sure that no older dll lies around.

**Comment by vanlooverenkoen** [comment]
Ow oke, I think I will wait for the nuget package, because I have no idea how to do that. I'm an android developer trying to make a .NET application :) Do you have any Idea when the nuget package will be updated?

**Comment by tebjan** [comment]
ok, no problem... probably next week. if not on the weekend already. greets!

**Comment by vanlooverenkoen** [comment]
Oke perfect I can wait :D the project needs to be completed at the start of January

**Comment by vanlooverenkoen** [comment]
Any idea when the nuget package will be updated?

**Comment by tebjan** [comment]
thanks for the remainder, it's up now... please test.

**Comment by vanlooverenkoen** [comment]
Omg this is just perfect, thank you so much. It works just perfect. This is the end of my project. Thank you so much 💯
