### ISSUE TITLE
FatalExecutionEngineError (0xc0000005)

### ISSUE THREAD

**Issue by kddlb** [tebjan/Sanford.Multimedia.Midi#15]
I compiled from source.

**Comment by tebjan** [comment]
the info in this issue is a bit sparse... can you explain what you did and how you used the code in order to get this error?

**Comment by kddlb** [comment]
This is where the bulk of MIDI processing is: https://github.com/kddlb/MidiPort/blob/master/MIDIPort/Form1.cs

**Comment by tebjan** [comment]
ok, i would recommend to attach the debugger and check at which exact command with what kind of bytes this happens...

**Comment by kode54** [comment]
It crashes with the heap corruption at the execution of midiIn.StartRecording();

Last time I tried debugging the same issue in a different MIDI input implementation, it crashed inside the MIDI callback for the MOM_OPEN message, as soon as that callback started performing memory allocation or manipulation for something as simple as string manipulation.

**Comment by tebjan** [comment]
maybe a calling convention or a p/invoke type is wrong... but i never had problems like that. what windows and which midi device are you using when that error happens?
