### ISSUE TITLE
Winmm Issue

### ISSUE THREAD

**Issue by DillonBroadus** [tebjan/Sanford.Multimedia.Midi#17]
In the README as well as on Nuget it states that this project "works on Mono" which is not the case for other non-Windows platforms since winmm.dll is required for this library to work (unless I've missed something).

**Comment by tebjan** [comment]
hello, i am not the original author of the library, i just put it on github and improved some things. the description was copied from somewhere... maybe its false in that regard. or it means mono on windows works.

**Comment by IainMNorman** [comment]
I did once look into hooking into OSX MIDI APIs for the project that I used SMM for. Didn't get the time to progress that during work though unfortunately. I'll PR the readme and clarify.

**Comment by DillonBroadus** [comment]
@IainMNorman The README may very well be using Mono in the sense of Mono vs. Stereo. Maybe just a slight clarification for those who use C# on other platforms.

**Comment by IainMNorman** [comment]
That's a good point. Perhaps it should say "Mono framework compatible" to be entirely clear.

**Comment by tebjan** [comment]
yep, clarified!
