### ISSUE TITLE
Close a disconnected MIDI device?

### ISSUE THREAD

**Issue by vanlooverenkoen** [tebjan/Sanford.Multimedia.Midi#20]
What is the best way to close a disconnected MIDI device? because if I call ` _inDevice?.StopRecording();` when the device has already been disconnected an exception is raised.

**Comment by IainMNorman** [comment]
Could you wrap it in a try catch, or could you check if it's connected before closing?

**Comment by vanlooverenkoen** [comment]
Yes, but after the StopRecodring(); I always call close() but this completely locks my application.

**Comment by tebjan** [comment]
how about only calling Dispose?

**Comment by tebjan** [comment]
closing this as it seems to be a usage problem. i wouldn't catch that inside the library operation since the exception can help developers finding bugs. if someone thinks otherwise please leave a comment here and we can re-discuss.
