### ISSUE TITLE
Doesn't work when upgrading to  beyond .NET 3.5

### ISSUE THREAD

**Issue by KasperHoldum** [tebjan/Sanford.Multimedia.Midi#24]
Hello,

I tried to run the midi watcher application in .NET 4.6.1. This causes the midi watcher app to fail when clicking the start button.

If I force the app to run 32-bit then it works flawlessly, so I assume it's a 64-bit issue.

I can see that you are working with CKKING on some fixes to the header structs. Any chance either of those will fix this issue?

**Comment by tebjan** [comment]
hello, the project should be set to AnyCPU. this works for both, 32 and 64 bit. i've just compiled and started the MidiWatcher without any problem. I am on Win10 64-bit. make sure that the midi driver is set correct and that it is not used by another program:
https://github.com/tebjan/Sanford.Multimedia.Midi/blob/master/Demo/MidiWatcher/Form1.cs#L41

**Comment by KasperHoldum** [comment]
Hmm. Seems I was stuck with a version a bit older than what is currently in this repo. I verified that it works in both 64-bit and 32-bit mode in .NET 4.6.1

**Comment by tebjan** [comment]
good to hear, where did you get it? was it the nuget?

**Comment by KasperHoldum** [comment]
I originally tried out the library quite a while ago. I assumed it was not being maintained anymore, so when I got the project back out of the drawers I never thought to fetch the latest code from here. 

I originally downloaded the code as zip from github.

**Comment by tebjan** [comment]
ah, very good. i just uploaded version 6.5.0 to nuget.org with a fix for PPQN values in midi files.
