### ISSUE TITLE
Why is the toolkit infamous?

### ISSUE THREAD

**Issue by ghost** [tebjan/Sanford.Multimedia.Midi#31]
Any reason to worry while using this? It's not clear from the description.

**Comment by tebjan** [comment]
that's an understatement in english language, don't take it literally. it means the famous toolkit, i.e. the first result on google.

**Comment by ghost** [comment]
I'm not sure I follow, infamous means "famous for all the wrong reasons", e.g. "the infamous serial killer".

**Comment by tebjan** [comment]
I see how that causes confusion, updated.
