### ISSUE TITLE
Device ID out of range (wine)

### ISSUE THREAD

**Issue by ednos** [tebjan/Sanford.Multimedia.Midi#32]
Using this library indirectly via [MontyLeGueux/Lutebot-2](https://github.com/MontyLeGueux/Lutebot-2), using `wine-4.17` on Fedora 30, I always get this error:
```Unhandled Exception:
Sanford.Multimedia.Midi.OutputDeviceException: A device ID has been used that is out of range for your system.
  at Sanford.Multimedia.Midi.OutputDevice..ctor (System.Int32 deviceID) [0x00056] in <b6d7dddb68bd429491388919abe6639c>:0 
```

I understand that this is likely a problem with the other software, but—what does this error mean?

**Comment by tebjan** [comment]
if you open a device, you have to pass in an integer that specifies the driver number. it seems that the number is too high or too low or that the system doesn't detect any midi devices.

**Comment by ednos** [comment]
Thanks for the quick response! The problem was indeed a lack of devices, and correcting my wine audio configuration fixed the problem.

**Comment by arsium** [comment]
> Thanks for the quick response! The problem was indeed a lack of devices, and correcting my wine audio configuration fixed the problem.

How did you fix ?
