### ISSUE TITLE
.Net v4.5 Version

### ISSUE THREAD

**Issue by J0nKn1ght** [tebjan/Sanford.Multimedia.Midi#7]
Hi,
I'm trying to compile this for .Net v4.5/4.6, but there is an interop issue that causes an exception on the following line in the InputDeviceMessaging.cs file (line 152):

`MidiHeader header = (MidiHeader)Marshal.PtrToStructure(headerPtr, typeof(MidiHeader));`

The exception is:
Additional information: The runtime has encountered a fatal error. The address of the error was at 0x24e7cfa4, on thread 0x108c. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.

I'm obviously not an interop expert, so I was wondering if you knew of a workaround for this exception?

Thanks.

**Comment by mweetman2** [comment]
Hi
Take a look at the other issue raised for this project. I think this is the same problem.

**Comment by J0nKn1ght** [comment]
Thanks, @mweetman2 - I should have read the other issue more closely! I'll close this one.

**Comment by mweetman2** [comment]
Great. I saw the same issue as you, then started looking at the HandleSysExMessage routine, & couldn’t see why it was being called at all. The explanation of truncated pointers would seem to be a good suggestion from uckuper.

Regards

Martin Weetman

Phone +44 7798 903766

http://www.weetman.com
